services:
  db:
    image: postgres
    container_name: express-auth-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: express-auth-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data